#!/usr/bin/env bash
# Updates system and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Add a customer header to nginx
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restarts Nginx
sudo service nginx restart
