#!/usr/bin/env bash
# Updates system and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy frontend and backend
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg

listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 44.200.83.158:80 check
   server 17272-web-02 3.237.16.226:80 check
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
