#!/usr/bin/env bash
# Updates system and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy frontend and backend
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg

listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 200895-web-01 100.25.136.106:80 check
   server 200895-web-02 54.174.111.199:80 check
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
