#!/usr/bin/env bash
This scripts terminates the 4-to_infinity_and_beyond process

# Define Process name to kill
p_name="7-highlander"

# Get the PID
pid=$(pgrep -f "$p_name")

# Check if process is running
if [ -z "$pid" ]
then
        exit
else
        kill "$pid"
fi
