#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinetly
# with a sleep 2 in between iterations
# Displays "I am invicible!!!" when receiving a SIGTERM signal

#Declare variables
i=0

# Define function to handle SIGTERM signal
function sigterm_handler()
{
    echo "I am invincible!!!"
}
# Trap the function as signal handler of SIGTERM
trap sigterm_handler SIGTERM

# Start while loop to loop indefinetly
while [ "$i" -eq 0 ]
do
    echo "To infinity and beyond"
    sleep 2
done
