#!/usr/bin/env bash
# This script displays "Best School" 10 times and "Hi" at the 9th iteration

i=0
while [ "$i" -lt 11 ]
do
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
