#!/usr/bin/env bash
# This script deals with superstitious numbers

i=1

while [ "$i" -le 20 ]
do
    case $i in
	1)
	    echo "$i"
	    ;;
        2)
            echo "$i"
            ;;
        3)
            echo "$i"
            ;;
	4)
	    echo "$i"
	    echo "bad luck from China"
	    ;;
        5)
            echo "$i"
            ;;
        6)
            echo "$i"
            ;;
	7)
            echo "$i"
            ;;
        8)
            echo "$i"
            ;;

	9)
	    echo "$i"
	    echo "bad luck from Japan"
	    ;;
        10)
            echo "$i"
            ;;
        11)
            echo "$i"
            ;;
        12)
            echo "$i"
            ;;
        13)
            echo "$i"
            ;;
        14)
            echo "$i"
            ;;
        15)
            echo "$i"
            ;;
        16)
            echo "$i"
            ;;

	17)
	    echo "$i"
	    echo "bad luck from Italy"
	    ;;
        18)
            echo "$i"
            ;;
        19)
            echo "$i"
            ;;
        20)
            echo "$i"
            ;;
    esac
    ((i++))

done
