#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

hr=0

while [ "$hr" -lt 12 ]
do
    echo "Hour: $hr"
    min=0
    while [ "$min" -le 59 ]
    do
	echo "$min"
	min=$((min+1))
    done
    hr=$((hr+1))
done
