#!/usr/bin/env bash
# This script configures an Ubuntu server
# Requirements
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.updated
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.updated
cp -f ~/hosts.updated /etc/hosts