#!/usr/bin/env bash
#script that configures nginx to run as nginx user and group
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
pkill -9 apache2
su nginx -c "service nginx restart"
